package com.payrollx.template;

import java.util.List;

/**
 * Base template class implementing the Template Method Pattern for report generation.
 */
public abstract class ReportGenerator<T> {

    /**
     * Template Method defining the structure of report generation.
     */
    public final String generateReport(String title, List<T> data) {
        StringBuilder sb = new StringBuilder();
        sb.append(generateHeader(title));
        sb.append("\n");
        sb.append(generateBody(data));
        sb.append("\n");
        sb.append(generateFooter());
        return sb.toString();
    }

    protected abstract String generateHeader(String title);
    
    protected abstract String generateBody(List<T> data);
    
    protected String generateFooter() {
        return "========================================================================\n" +
               "Generated by PayrollX AI | Date: " + java.time.LocalDate.now() + "\n" +
               "========================================================================\n";
    }
}
